-- public.users definition

-- Drop table

-- DROP TABLE public.users;

-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

COMMENT ON SCHEMA public IS 'standard public schema';

-- DROP SEQUENCE public.audit_logs_id_seq;

CREATE SEQUENCE public.audit_logs_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.documents_archive_id_seq;

CREATE SEQUENCE public.documents_archive_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.password_reset_tokens_id_seq;

CREATE SEQUENCE public.password_reset_tokens_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.pbidentity_roles_id_seq;

CREATE SEQUENCE public.pbidentity_roles_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.permissions_id_seq;

CREATE SEQUENCE public.permissions_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.sessions_id_seq;

CREATE SEQUENCE public.sessions_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.user_schemas_id_seq;

CREATE SEQUENCE public.user_schemas_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.users_id_seq;

CREATE SEQUENCE public.users_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 100
	CACHE 1
	NO CYCLE;-- public.password_reset_tokens definition

-- Drop table

-- DROP TABLE public.password_reset_tokens;

CREATE TABLE public.password_reset_tokens (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	platform_user_id int4 NOT NULL,
	"token" varchar(255) NOT NULL,
	expires_at timestamp NOT NULL,
	is_used bool DEFAULT false NOT NULL,
	create_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	update_date timestamp DEFAULT now() NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	hashed_token text NULL,
	CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_prt_expires_unused ON public.password_reset_tokens USING btree (expires_at) WHERE (is_used = false);
CREATE INDEX idx_prt_token_unused ON public.password_reset_tokens USING btree (token) WHERE (is_used = false);
CREATE INDEX idx_prt_user_unused ON public.password_reset_tokens USING btree (platform_user_id) WHERE (is_used = false);

-- Table Triggers

create trigger trg_audit_password_reset_tokens before
insert
    or
update
    on
    public.password_reset_tokens for each row execute function fn_set_audit_columns();
create trigger trg_password_reset_tokens_audit after
insert
    or
delete
    or
update
    on
    public.password_reset_tokens for each row execute function fn_audit_trigger();
ALTER TABLE public.password_reset_tokens ENABLE ROW LEVEL SECURITY;

-- Table Policies

CREATE POLICY admin_full_access ON public.password_reset_tokens
 AS PERMISSIVE
 FOR ALL
 USING ((CURRENT_USER = ANY (ARRAY['neondb_owner'::name, 'admin'::name, 'cloud_admin'::name])));
CREATE POLICY user_delete_access ON public.password_reset_tokens
 AS PERMISSIVE
 FOR DELETE
 USING ((platform_user_id = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)));
CREATE POLICY user_own_access ON public.password_reset_tokens
 AS PERMISSIVE
 FOR ALL
 USING ((platform_user_id = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)));
CREATE POLICY user_update_access ON public.password_reset_tokens
 AS PERMISSIVE
 FOR UPDATE
 USING ((platform_user_id = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)))
 WITH CHECK ((platform_user_id = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)));


-- public.user_roles_archive definition

-- Drop table

-- DROP TABLE public.user_roles_archive;

CREATE TABLE public.user_roles_archive (
	id int4 NULL,
	user_id int4 NULL,
	role_id int4 NULL,
	operation_user_id int4 NULL,
	archive_action varchar(50) NULL,
	archive_date timestamp NULL,
	create_date timestamp DEFAULT now() NULL,
	update_date timestamp DEFAULT now() NULL,
	updated_by int4 NULL
);

-- Table Triggers

create trigger trg_audit_user_roles_archive before
insert
    or
update
    on
    public.user_roles_archive for each row execute function fn_set_audit_columns();
create trigger trg_user_roles_archive_audit after
insert
    or
delete
    or
update
    on
    public.user_roles_archive for each row execute function fn_audit_trigger();
ALTER TABLE public.user_roles_archive ENABLE ROW LEVEL SECURITY;

-- Table Policies

CREATE POLICY admin_full_access ON public.user_roles_archive
 AS PERMISSIVE
 FOR ALL
 USING ((CURRENT_USER = ANY (ARRAY['neondb_owner'::name, 'admin'::name, 'cloud_admin'::name])));
CREATE POLICY user_update_access ON public.user_roles_archive
 AS PERMISSIVE
 FOR UPDATE
 USING ((user_id = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)))
 WITH CHECK ((user_id = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)));


-- public.users_auth_backup_20260418 definition

-- Drop table

-- DROP TABLE public.users_auth_backup_20260418;

CREATE TABLE public.users_auth_backup_20260418 (
	id int4 NULL,
	"password" varchar(128) NULL,
	password_reset_token varchar(128) NULL,
	password_reset_expires timestamp NULL,
	temp_password varchar(100) NULL,
	must_change_password bool NULL,
	password_changed_by varchar(10) NULL,
	password_changed_at timestamptz NULL,
	last_login timestamptz NULL,
	is_staff bool NULL,
	is_superuser bool NULL
);


-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
	id int4 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 100 CACHE 1 NO CYCLE) NOT NULL,
	username varchar(50) NOT NULL,
	email varchar(254) NOT NULL,
	password_hash varchar(255) NOT NULL,
	first_name varchar(100) NULL,
	last_name varchar(100) NULL,
	user_type varchar(30) NULL,
	is_active bool DEFAULT true NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	create_date timestamptz DEFAULT now() NOT NULL,
	update_date timestamptz DEFAULT now() NOT NULL,
	profile_image_url varchar(500) NULL,
	phone varchar(20) NULL,
	is_email_verified bool DEFAULT false NULL,
	email_verified_at timestamp NULL,
	language_code varchar(5) DEFAULT 'tr'::character varying NULL,
	gender varchar(10) NULL,
	title varchar(100) DEFAULT ''::character varying NULL,
	faculty varchar(200) DEFAULT ''::character varying NULL,
	department varchar(200) DEFAULT ''::character varying NULL,
	student_number varchar(12) NULL,
	CONSTRAINT chk_phone_tr CHECK (((phone)::text ~ '^\+90\d{10}$'::text)),
	CONSTRAINT chk_student_number_format CHECK (((student_number)::text ~ '^[0-9]{10,12}$'::text)),
	CONSTRAINT users_gender_check CHECK (((gender)::text = ANY (ARRAY[('male'::character varying)::text, ('female'::character varying)::text]))),
	CONSTRAINT users_pkey PRIMARY KEY (id),
	CONSTRAINT fk_users_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
	CONSTRAINT fk_users_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE UNIQUE INDEX idx_users_email ON public.users USING btree (email);
CREATE INDEX idx_users_email_active_partial ON public.users USING btree (email) WHERE (is_active = true);
CREATE INDEX idx_users_updated_by ON public.users USING btree (updated_by) WHERE (updated_by IS NOT NULL);
CREATE INDEX idx_users_user_type ON public.users USING btree (user_type) WHERE (is_active = true);
CREATE UNIQUE INDEX idx_users_username ON public.users USING btree (username);

-- Table Triggers

create trigger trg_audit_users before
insert
    or
update
    on
    public.users for each row execute function fn_set_audit_columns_users();
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Table Policies

CREATE POLICY admin_full_access ON public.users
 AS PERMISSIVE
 FOR ALL
 USING ((CURRENT_USER = ANY (ARRAY['neondb_owner'::name, 'admin'::name, 'cloud_admin'::name])));
CREATE POLICY user_delete_access ON public.users
 AS PERMISSIVE
 FOR DELETE
 USING ((created_by = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)));
CREATE POLICY user_insert_access ON public.users
 AS PERMISSIVE
 FOR INSERT
 WITH CHECK ((created_by = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER))));
CREATE POLICY user_own_access ON public.users
 AS PERMISSIVE
 FOR SELECT
 USING (((id = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER))) OR (created_by = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)))));
CREATE POLICY user_update_access ON public.users
 AS PERMISSIVE
 FOR UPDATE
 USING ((created_by = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)))
 WITH CHECK ((created_by = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)));


-- public.audit_logs definition

-- Drop table

-- DROP TABLE public.audit_logs;

CREATE TABLE public.audit_logs (
	id serial4 NOT NULL,
	user_id int4 NULL,
	table_name varchar NOT NULL,
	record_id int4 NULL,
	"action" varchar NOT NULL,
	old_data jsonb NULL,
	new_data jsonb NULL,
	create_date timestamptz DEFAULT now() NULL,
	update_date timestamptz DEFAULT now() NULL,
	operation_user_id int4 NULL,
	archive_action varchar(20) NOT NULL,
	archive_date timestamp DEFAULT now() NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
	CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE INDEX idx_audit_action_date ON public.audit_logs USING btree (archive_action, create_date DESC);
CREATE INDEX idx_audit_create_date ON public.audit_logs USING btree (create_date DESC);
CREATE INDEX idx_audit_operation_user ON public.audit_logs USING btree (operation_user_id);
CREATE INDEX idx_audit_table_record ON public.audit_logs USING btree (table_name, record_id);
CREATE INDEX idx_audit_table_record_date ON public.audit_logs USING btree (table_name, record_id, create_date DESC);
CREATE INDEX idx_audit_user_date ON public.audit_logs USING btree (user_id, create_date DESC);
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Table Policies

CREATE POLICY admin_full_access ON public.audit_logs
 AS PERMISSIVE
 FOR ALL
 USING ((CURRENT_USER = ANY (ARRAY['neondb_owner'::name, 'admin'::name, 'cloud_admin'::name])));
CREATE POLICY user_delete_access ON public.audit_logs
 AS PERMISSIVE
 FOR DELETE
 USING ((user_id = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)));
CREATE POLICY user_own_access ON public.audit_logs
 AS PERMISSIVE
 FOR ALL
 USING ((user_id = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)));
CREATE POLICY user_update_access ON public.audit_logs
 AS PERMISSIVE
 FOR UPDATE
 USING ((user_id = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)))
 WITH CHECK ((user_id = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)));


-- public.documents_archive definition

-- Drop table

-- DROP TABLE public.documents_archive;

CREATE TABLE public.documents_archive (
	id int4 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id int4 NOT NULL,
	document_type varchar(50) NOT NULL,
	original_filename varchar(255) NOT NULL,
	file_path varchar(500) NULL,
	is_active bool DEFAULT true NOT NULL,
	operation_user_id int4 NULL,
	archive_action varchar(50) NOT NULL,
	archive_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	create_date timestamptz DEFAULT now() NOT NULL,
	update_date timestamptz DEFAULT now() NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	file_data bytea NULL,
	mime_type varchar(150) NULL,
	CONSTRAINT constraint_name CHECK (((archive_action)::text = ANY (ARRAY[('INSERT'::character varying)::text, ('UPDATE'::character varying)::text, ('DELETE'::character varying)::text]))),
	CONSTRAINT pk_documents_archive PRIMARY KEY (id),
	CONSTRAINT fk_documents_archive_operation_user_id FOREIGN KEY (operation_user_id) REFERENCES public.users(id),
	CONSTRAINT fk_documents_archive_user_id FOREIGN KEY (user_id) REFERENCES public.users(id)
);

-- Table Triggers

create trigger trg_audit_documents_archive before
insert
    or
update
    on
    public.documents_archive for each row execute function fn_set_audit_columns_create_date();
create trigger trg_documents_archive_audit after
insert
    or
delete
    or
update
    on
    public.documents_archive for each row execute function fn_audit_trigger();
ALTER TABLE public.documents_archive ENABLE ROW LEVEL SECURITY;

-- Table Policies

CREATE POLICY admin_full_access ON public.documents_archive
 AS PERMISSIVE
 FOR ALL
 USING ((CURRENT_USER = ANY (ARRAY['neondb_owner'::name, 'admin'::name, 'cloud_admin'::name])));
CREATE POLICY user_delete_access ON public.documents_archive
 AS PERMISSIVE
 FOR DELETE
 USING ((user_id = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)));
CREATE POLICY user_own_access ON public.documents_archive
 AS PERMISSIVE
 FOR ALL
 USING ((user_id = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)));
CREATE POLICY user_update_access ON public.documents_archive
 AS PERMISSIVE
 FOR UPDATE
 USING ((user_id = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)))
 WITH CHECK ((user_id = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)));


-- public.permissions definition

-- Drop table

-- DROP TABLE public.permissions;

CREATE TABLE public.permissions (
	id serial4 NOT NULL,
	code varchar(100) NOT NULL,
	description varchar(255) NULL,
	create_date timestamp DEFAULT now() NULL,
	update_date timestamp DEFAULT now() NULL,
	operation_user_id int4 NOT NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	CONSTRAINT permissions_code_key UNIQUE (code),
	CONSTRAINT permissions_pkey PRIMARY KEY (id),
	CONSTRAINT permissions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);

-- Table Triggers

create trigger trg_audit_permissions before
insert
    or
update
    on
    public.permissions for each row execute function fn_set_audit_columns();
create trigger trg_permissions_audit after
insert
    or
delete
    or
update
    on
    public.permissions for each row execute function fn_audit_trigger();
ALTER TABLE public.permissions ENABLE ROW LEVEL SECURITY;

-- Table Policies

CREATE POLICY admin_full_access ON public.permissions
 AS PERMISSIVE
 FOR ALL
 USING ((CURRENT_USER = ANY (ARRAY['neondb_owner'::name, 'admin'::name, 'cloud_admin'::name])));
CREATE POLICY user_delete_access ON public.permissions
 AS PERMISSIVE
 FOR DELETE
 USING ((created_by = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)));
CREATE POLICY user_own_access ON public.permissions
 AS PERMISSIVE
 FOR ALL
 USING ((created_by = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)));
CREATE POLICY user_update_access ON public.permissions
 AS PERMISSIVE
 FOR UPDATE
 USING ((created_by = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)))
 WITH CHECK ((created_by = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)));


-- public.role_permissions_archive definition

-- Drop table

-- DROP TABLE public.role_permissions_archive;

CREATE TABLE public.role_permissions_archive (
	id int4 NULL,
	role_id int4 NULL,
	permission_id int4 NULL,
	archive_action varchar(50) NULL,
	archive_date timestamp NULL,
	create_date timestamp DEFAULT now() NULL,
	update_date timestamp DEFAULT now() NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	CONSTRAINT role_permissions_archive_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);

-- Table Triggers

create trigger trg_audit_role_permissions_archive before
insert
    or
update
    on
    public.role_permissions_archive for each row execute function fn_set_audit_columns();
create trigger trg_role_permissions_archive_audit after
insert
    or
delete
    or
update
    on
    public.role_permissions_archive for each row execute function fn_audit_trigger();
ALTER TABLE public.role_permissions_archive ENABLE ROW LEVEL SECURITY;

-- Table Policies

CREATE POLICY admin_full_access ON public.role_permissions_archive
 AS PERMISSIVE
 FOR ALL
 USING ((CURRENT_USER = ANY (ARRAY['neondb_owner'::name, 'admin'::name, 'cloud_admin'::name])));
CREATE POLICY user_own_access ON public.role_permissions_archive
 AS PERMISSIVE
 FOR ALL
 USING ((created_by = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)));
CREATE POLICY user_update_access ON public.role_permissions_archive
 AS PERMISSIVE
 FOR UPDATE
 USING ((created_by = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)))
 WITH CHECK ((created_by = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)));


-- public.roles definition

-- Drop table

-- DROP TABLE public.roles;

CREATE TABLE public.roles (
	id serial4 NOT NULL,
	"name" varchar(50) NOT NULL,
	description varchar(255) NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	create_date timestamptz DEFAULT now() NOT NULL,
	update_date timestamptz DEFAULT now() NOT NULL,
	is_active bool DEFAULT true NULL,
	CONSTRAINT pbidentity_roles_name_key UNIQUE (name),
	CONSTRAINT pbidentity_roles_pkey PRIMARY KEY (id),
	CONSTRAINT fk_roles_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
	CONSTRAINT fk_roles_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id)
);

-- Table Triggers

create trigger trg_audit_roles before
insert
    or
update
    on
    public.roles for each row execute function fn_set_audit_columns();
create trigger trg_roles_audit after
insert
    or
delete
    or
update
    on
    public.roles for each row execute function fn_audit_trigger();
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;

-- Table Policies

CREATE POLICY admin_full_access ON public.roles
 AS PERMISSIVE
 FOR ALL
 USING ((CURRENT_USER = ANY (ARRAY['neondb_owner'::name, 'admin'::name, 'cloud_admin'::name])));
CREATE POLICY user_delete_access ON public.roles
 AS PERMISSIVE
 FOR DELETE
 USING ((created_by = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)));
CREATE POLICY user_own_access ON public.roles
 AS PERMISSIVE
 FOR SELECT
 USING ((created_by = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)));
CREATE POLICY user_update_access ON public.roles
 AS PERMISSIVE
 FOR UPDATE
 USING ((created_by = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)))
 WITH CHECK ((created_by = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)));


-- public.sessions definition

-- Drop table

-- DROP TABLE public.sessions;

CREATE TABLE public.sessions (
	id serial4 NOT NULL,
	user_id int4 NOT NULL,
	"token" varchar NOT NULL,
	expires_at timestamptz NOT NULL,
	revoked bool DEFAULT false NULL,
	create_date timestamptz DEFAULT now() NULL,
	update_date timestamptz DEFAULT now() NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	CONSTRAINT sessions_pkey PRIMARY KEY (id),
	CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE INDEX idx_sessions_expires_at ON public.sessions USING btree (expires_at) WHERE (revoked = false);
CREATE INDEX idx_sessions_token_not_revoked ON public.sessions USING btree (token) WHERE (revoked = false);
CREATE INDEX idx_sessions_user_active ON public.sessions USING btree (user_id, expires_at) WHERE (revoked = false);

-- Table Triggers

create trigger trg_audit_sessions before
insert
    or
update
    on
    public.sessions for each row execute function fn_set_audit_columns();
create trigger trg_sessions_audit after
insert
    or
delete
    or
update
    on
    public.sessions for each row execute function fn_audit_trigger();
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;

-- Table Policies

CREATE POLICY admin_full_access ON public.sessions
 AS PERMISSIVE
 FOR ALL
 USING ((CURRENT_USER = ANY (ARRAY['neondb_owner'::name, 'admin'::name, 'cloud_admin'::name])));
CREATE POLICY user_delete_access ON public.sessions
 AS PERMISSIVE
 FOR DELETE
 USING ((user_id = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)));
CREATE POLICY user_own_access ON public.sessions
 AS PERMISSIVE
 FOR ALL
 USING ((user_id = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)));
CREATE POLICY user_update_access ON public.sessions
 AS PERMISSIVE
 FOR UPDATE
 USING ((user_id = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)))
 WITH CHECK ((user_id = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)));


-- public.user_auth definition

-- Drop table

-- DROP TABLE public.user_auth;

CREATE TABLE public.user_auth (
	user_id int4 NOT NULL,
	password_hash varchar(255) NOT NULL,
	password_reset_token varchar(255) NULL,
	password_reset_expires timestamp NULL,
	temp_password varchar(255) NULL,
	must_change_password bool DEFAULT false NOT NULL,
	password_changed_by int4 NULL,
	password_changed_at timestamp NULL,
	last_login timestamp NULL,
	is_staff bool DEFAULT false NOT NULL,
	is_superuser bool DEFAULT false NOT NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	created_by int4 NULL,
	updated_at timestamp NULL,
	updated_by int4 NULL,
	CONSTRAINT user_auth_pkey PRIMARY KEY (user_id),
	CONSTRAINT fk_user_auth_created_by FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL,
	CONSTRAINT fk_user_auth_password_changed_by FOREIGN KEY (password_changed_by) REFERENCES public.users(id) ON DELETE SET NULL,
	CONSTRAINT fk_user_auth_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id) ON DELETE SET NULL,
	CONSTRAINT fk_user_auth_user FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE INDEX idx_user_auth_created_by ON public.user_auth USING btree (created_by);
CREATE INDEX idx_user_auth_is_staff ON public.user_auth USING btree (is_staff);
CREATE INDEX idx_user_auth_is_superuser ON public.user_auth USING btree (is_superuser);
CREATE INDEX idx_user_auth_updated_by ON public.user_auth USING btree (updated_by);

-- Table Triggers

create trigger trg_user_auth_audit before
insert
    or
update
    on
    public.user_auth for each row execute function set_user_auth_audit();
ALTER TABLE public.user_auth ENABLE ROW LEVEL SECURITY;

-- Table Policies

CREATE POLICY user_auth_delete_own ON public.user_auth
 AS PERMISSIVE
 FOR DELETE
 USING ((user_id = ( SELECT us.user_id
   FROM user_schemas us
  WHERE ((us.schema_name)::text = CURRENT_USER))));
CREATE POLICY user_auth_insert_own ON public.user_auth
 AS PERMISSIVE
 FOR INSERT
 WITH CHECK ((user_id = ( SELECT us.user_id
   FROM user_schemas us
  WHERE ((us.schema_name)::text = CURRENT_USER))));
CREATE POLICY user_auth_select_own ON public.user_auth
 AS PERMISSIVE
 FOR SELECT
 USING ((user_id = ( SELECT us.user_id
   FROM user_schemas us
  WHERE ((us.schema_name)::text = CURRENT_USER))));
CREATE POLICY user_auth_update_own ON public.user_auth
 AS PERMISSIVE
 FOR UPDATE
 USING ((user_id = ( SELECT us.user_id
   FROM user_schemas us
  WHERE ((us.schema_name)::text = CURRENT_USER))))
 WITH CHECK ((user_id = ( SELECT us.user_id
   FROM user_schemas us
  WHERE ((us.schema_name)::text = CURRENT_USER))));


-- public.user_roles definition

-- Drop table

-- DROP TABLE public.user_roles;

CREATE TABLE public.user_roles (
	user_id int4 NOT NULL,
	role_id int4 NOT NULL,
	create_date timestamptz DEFAULT now() NULL,
	update_date timestamptz DEFAULT now() NULL,
	operation_user_id int4 NOT NULL,
	archive_action varchar(20) NULL,
	archive_date timestamptz DEFAULT now() NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	CONSTRAINT fk_ur_role FOREIGN KEY (role_id) REFERENCES public.roles(id) ON DELETE CASCADE,
	CONSTRAINT fk_ur_user FOREIGN KEY (user_id) REFERENCES public.users(id),
	CONSTRAINT fk_user_roles_operation_user FOREIGN KEY (operation_user_id) REFERENCES public.users(id),
	CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES public.roles(id)
);
CREATE INDEX idx_user_roles_role_id ON public.user_roles USING btree (role_id);
CREATE INDEX idx_user_roles_user_id ON public.user_roles USING btree (user_id);

-- Table Triggers

create trigger trg_user_roles_audit after
insert
    or
delete
    or
update
    on
    public.user_roles for each row execute function fn_audit_trigger();
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- Table Policies

CREATE POLICY admin_full_access ON public.user_roles
 AS PERMISSIVE
 FOR ALL
 USING ((CURRENT_USER = ANY (ARRAY['neondb_owner'::name, 'admin'::name, 'cloud_admin'::name])));
CREATE POLICY user_delete_access ON public.user_roles
 AS PERMISSIVE
 FOR DELETE
 USING ((user_id = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)));
CREATE POLICY user_insert_access ON public.user_roles
 AS PERMISSIVE
 FOR INSERT
 WITH CHECK (((user_id = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)) AND (created_by = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1))));
CREATE POLICY user_own_access ON public.user_roles
 AS PERMISSIVE
 FOR SELECT
 USING ((user_id = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)));
CREATE POLICY user_roles_insert_policy ON public.user_roles
 AS PERMISSIVE
 FOR INSERT
 WITH CHECK ((created_by = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)));
CREATE POLICY user_update_access ON public.user_roles
 AS PERMISSIVE
 FOR UPDATE
 USING ((user_id = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)))
 WITH CHECK ((user_id = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)));


-- public.user_schemas definition

-- Drop table

-- DROP TABLE public.user_schemas;

CREATE TABLE public.user_schemas (
	id bigserial NOT NULL,
	user_id int8 NOT NULL,
	schema_name varchar(100) NOT NULL,
	is_active bool DEFAULT true NOT NULL,
	created_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	update_date timestamp NULL,
	operation_user_id int8 NULL,
	archive_action varchar(20) NULL,
	archive_date timestamp NULL,
	created_by int8 NULL,
	updated_by int8 NULL,
	CONSTRAINT user_schemas_pkey PRIMARY KEY (id),
	CONSTRAINT fk_user_schemas_user FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE INDEX idx_user_schemas_schema_name ON public.user_schemas USING btree (schema_name) WHERE (is_active = true);
CREATE INDEX idx_user_schemas_user ON public.user_schemas USING btree (user_id);
CREATE UNIQUE INDEX ux_user_schemas_active ON public.user_schemas USING btree (user_id, schema_name) WHERE (is_active = true);

-- Table Triggers

create trigger trg_audit_user_schemas before
insert
    or
update
    on
    public.user_schemas for each row execute function fn_set_audit_columns_user_schemas();
create trigger trg_user_schemas_audit after
insert
    or
delete
    or
update
    on
    public.user_schemas for each row execute function fn_audit_trigger();
ALTER TABLE public.user_schemas ENABLE ROW LEVEL SECURITY;

-- Table Policies

CREATE POLICY admin_full_access ON public.user_schemas
 AS PERMISSIVE
 FOR ALL
 USING ((CURRENT_USER = 'neondb_owner'::name));
CREATE POLICY user_own_access ON public.user_schemas
 AS PERMISSIVE
 FOR ALL
 USING (((schema_name)::text = CURRENT_USER));
CREATE POLICY user_update_access ON public.user_schemas
 AS PERMISSIVE
 FOR UPDATE
 USING ((user_id = ( SELECT user_schemas_1.user_id
   FROM user_schemas user_schemas_1
  WHERE ((user_schemas_1.schema_name)::text = CURRENT_USER)
 LIMIT 1)))
 WITH CHECK ((user_id = ( SELECT user_schemas_1.user_id
   FROM user_schemas user_schemas_1
  WHERE ((user_schemas_1.schema_name)::text = CURRENT_USER)
 LIMIT 1)));


-- public.role_permissions definition

-- Drop table

-- DROP TABLE public.role_permissions;

CREATE TABLE public.role_permissions (
	role_id int4 NOT NULL,
	permission_id int4 NOT NULL,
	create_date timestamptz DEFAULT now() NULL,
	update_date timestamptz DEFAULT now() NULL,
	archive_action varchar(20) NULL,
	archive_date timestamptz DEFAULT now() NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	CONSTRAINT role_permissions_pkey PRIMARY KEY (role_id, permission_id),
	CONSTRAINT role_permissions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
	CONSTRAINT role_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.permissions(id),
	CONSTRAINT role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id)
);
CREATE INDEX idx_role_permissions_permission_id ON public.role_permissions USING btree (permission_id);

-- Table Triggers

create trigger trg_audit_role_permissions before
insert
    or
update
    on
    public.role_permissions for each row execute function fn_set_audit_columns();
create trigger trg_role_permissions_audit after
insert
    or
delete
    or
update
    on
    public.role_permissions for each row execute function fn_audit_trigger();
ALTER TABLE public.role_permissions ENABLE ROW LEVEL SECURITY;

-- Table Policies

CREATE POLICY admin_full_access ON public.role_permissions
 AS PERMISSIVE
 FOR ALL
 USING ((CURRENT_USER = ANY (ARRAY['neondb_owner'::name, 'admin'::name, 'cloud_admin'::name])));
CREATE POLICY user_delete_access ON public.role_permissions
 AS PERMISSIVE
 FOR DELETE
 USING ((created_by = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)));
CREATE POLICY user_own_access ON public.role_permissions
 AS PERMISSIVE
 FOR ALL
 USING ((created_by = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)));
CREATE POLICY user_update_access ON public.role_permissions
 AS PERMISSIVE
 FOR UPDATE
 USING ((created_by = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)))
 WITH CHECK ((created_by = ( SELECT user_schemas.user_id
   FROM user_schemas
  WHERE ((user_schemas.schema_name)::text = CURRENT_USER)
 LIMIT 1)));


-- public.v_users_public source

CREATE OR REPLACE VIEW public.v_users_public
AS SELECT id,
    username,
    email
   FROM users
  WHERE is_active = true;



-- DROP FUNCTION public.armor(bytea, _text, _text);

CREATE OR REPLACE FUNCTION public.armor(bytea, text[], text[])
 RETURNS text
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pg_armor$function$
;

-- DROP FUNCTION public.armor(bytea);

CREATE OR REPLACE FUNCTION public.armor(bytea)
 RETURNS text
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pg_armor$function$
;

-- DROP FUNCTION public.change_user_password(int4, text);

CREATE OR REPLACE FUNCTION public.change_user_password(p_user_id integer, p_password_hash text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
    UPDATE public.users
    SET password_hash = p_password_hash
    WHERE id = p_user_id;
END;
$function$
;

-- DROP FUNCTION public.crypt(text, text);

CREATE OR REPLACE FUNCTION public.crypt(text, text)
 RETURNS text
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pg_crypt$function$
;

-- DROP FUNCTION public.dearmor(text);

CREATE OR REPLACE FUNCTION public.dearmor(text)
 RETURNS bytea
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pg_dearmor$function$
;

-- DROP FUNCTION public.decrypt(bytea, bytea, text);

CREATE OR REPLACE FUNCTION public.decrypt(bytea, bytea, text)
 RETURNS bytea
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pg_decrypt$function$
;

-- DROP FUNCTION public.decrypt_iv(bytea, bytea, bytea, text);

CREATE OR REPLACE FUNCTION public.decrypt_iv(bytea, bytea, bytea, text)
 RETURNS bytea
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pg_decrypt_iv$function$
;

-- DROP FUNCTION public.digest(bytea, text);

CREATE OR REPLACE FUNCTION public.digest(bytea, text)
 RETURNS bytea
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pg_digest$function$
;

-- DROP FUNCTION public.digest(text, text);

CREATE OR REPLACE FUNCTION public.digest(text, text)
 RETURNS bytea
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pg_digest$function$
;

-- DROP FUNCTION public.encrypt(bytea, bytea, text);

CREATE OR REPLACE FUNCTION public.encrypt(bytea, bytea, text)
 RETURNS bytea
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pg_encrypt$function$
;

-- DROP FUNCTION public.encrypt_iv(bytea, bytea, bytea, text);

CREATE OR REPLACE FUNCTION public.encrypt_iv(bytea, bytea, bytea, text)
 RETURNS bytea
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pg_encrypt_iv$function$
;

-- DROP FUNCTION public.fn_audit_trigger();

CREATE OR REPLACE FUNCTION public.fn_audit_trigger()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_record_id INTEGER;
    v_user_id BIGINT;
    v_op_user_id BIGINT;
    v_action VARCHAR(20);
BEGIN
    BEGIN
        v_user_id := current_setting('app.current_user_id', TRUE)::BIGINT;
    EXCEPTION
        WHEN OTHERS THEN
            v_user_id := NULL;
    END;

    IF v_user_id IS NULL OR v_user_id = 0 THEN
        SELECT us.user_id
        INTO v_user_id
        FROM public.user_schemas us
        WHERE us.schema_name = current_user
        LIMIT 1;
    END IF;

    v_op_user_id := v_user_id;

    IF TG_OP = 'DELETE' THEN
        v_action := 'DELETE';
    ELSIF TG_OP = 'UPDATE' THEN
        v_action := 'UPDATE';
    ELSE
        v_action := 'INSERT';
    END IF;

    -- record_id belirleme
    IF TG_TABLE_NAME = 'user_roles' THEN
        IF TG_OP = 'DELETE' THEN
            v_record_id := OLD.user_id;
        ELSE
            v_record_id := NEW.user_id;
        END IF;
    ELSE
        IF TG_OP = 'DELETE' THEN
            v_record_id := OLD.id;
        ELSE
            v_record_id := NEW.id;
        END IF;
    END IF;

    IF TG_OP = 'INSERT' THEN
        BEGIN
            NEW.created_by := v_user_id;
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END IF;

    INSERT INTO public.audit_logs(
        user_id,
        table_name,
        record_id,
        action,
        archive_action,
        old_data,
        new_data,
        create_date,
        update_date,
        operation_user_id,
        archive_date
    )
    VALUES (
        v_user_id,
        TG_TABLE_NAME,
        v_record_id,
        v_action,
        v_action,
        CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE to_jsonb(OLD) END,
        CASE WHEN TG_OP = 'DELETE' THEN NULL ELSE to_jsonb(NEW) END,
        NOW(),
        NOW(),
        v_op_user_id,
        NOW()
    );

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    ELSE
        RETURN NEW;
    END IF;
END;
$function$
;

COMMENT ON FUNCTION public.fn_audit_trigger() IS 'AFTER INSERT/UPDATE/DELETE triggerı.
Amac: Her veri degisikligini audit_logs tablosuna kaydeder.
- app.current_user_id session degiskeninden kullanici ID alir
- Bulamazsa user_schemas tablosundan current_user ile eslestirir
- INSERT: old_data NULL, new_data dolu
- UPDATE: hem old_data hem new_data dolu
- DELETE: old_data dolu, new_data NULL
- created_by kolonunu da INSERT sirasinda set etmeye calisir';

-- DROP FUNCTION public.fn_set_audit_columns();

CREATE OR REPLACE FUNCTION public.fn_set_audit_columns()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_user_id BIGINT;
BEGIN
    SELECT us.user_id
    INTO v_user_id
    FROM public.user_schemas us
    WHERE us.schema_name = current_user
      AND us.is_active = TRUE
    LIMIT 1;

    IF TG_OP = 'INSERT' THEN
        IF EXISTS (
            SELECT 1 FROM information_schema.columns 
            WHERE table_name = TG_TABLE_NAME 
              AND column_name = 'created_at'
        ) THEN
            NEW.created_at := COALESCE(NEW.created_at, CURRENT_TIMESTAMP);
        END IF;

        IF EXISTS (
            SELECT 1 FROM information_schema.columns 
            WHERE table_name = TG_TABLE_NAME 
              AND column_name = 'created_by'
        ) THEN
            NEW.created_by := COALESCE(NEW.created_by, v_user_id);
        END IF;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = TG_TABLE_NAME 
          AND column_name = 'updated_at'
    ) THEN
        NEW.updated_at := CURRENT_TIMESTAMP;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = TG_TABLE_NAME 
          AND column_name = 'updated_by'
    ) THEN
        NEW.updated_by := v_user_id;
    END IF;

    RETURN NEW;
END;
$function$
;

COMMENT ON FUNCTION public.fn_set_audit_columns() IS 'BEFORE INSERT/UPDATE triggerı.
Amac: create_date, update_date, created_by, updated_by kolonlarini otomatik doldurur.
- INSERT: create_date ve created_by set edilir
- INSERT/UPDATE: update_date ve updated_by her zaman set edilir
- app.current_user_id session degiskeninden kullanici ID alinir
- Developer manuel set etmek zorunda kalmaz, atlanamaz';

-- DROP FUNCTION public.fn_set_audit_columns_create_date();

CREATE OR REPLACE FUNCTION public.fn_set_audit_columns_create_date()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.create_date IS NULL THEN
            NEW.create_date := CURRENT_TIMESTAMP;
        END IF;
    END IF;

    NEW.update_date := CURRENT_TIMESTAMP;

    RETURN NEW;
END;
$function$
;

-- DROP FUNCTION public.fn_set_audit_columns_user_schemas();

CREATE OR REPLACE FUNCTION public.fn_set_audit_columns_user_schemas()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.created_date IS NULL THEN
            NEW.created_date := CURRENT_TIMESTAMP;
        END IF;
    END IF;

    NEW.update_date := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$function$
;

-- DROP FUNCTION public.fn_set_audit_columns_users();

CREATE OR REPLACE FUNCTION public.fn_set_audit_columns_users()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.create_date IS NULL THEN
            NEW.create_date := CURRENT_TIMESTAMP;
        END IF;
    END IF;

    NEW.update_date := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$function$
;

-- DROP FUNCTION public.gen_random_bytes(int4);

CREATE OR REPLACE FUNCTION public.gen_random_bytes(integer)
 RETURNS bytea
 LANGUAGE c
 PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pg_random_bytes$function$
;

-- DROP FUNCTION public.gen_random_uuid();

CREATE OR REPLACE FUNCTION public.gen_random_uuid()
 RETURNS uuid
 LANGUAGE c
 PARALLEL SAFE
AS '$libdir/pgcrypto', $function$pg_random_uuid$function$
;

-- DROP FUNCTION public.gen_salt(text);

CREATE OR REPLACE FUNCTION public.gen_salt(text)
 RETURNS text
 LANGUAGE c
 PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pg_gen_salt$function$
;

-- DROP FUNCTION public.gen_salt(text, int4);

CREATE OR REPLACE FUNCTION public.gen_salt(text, integer)
 RETURNS text
 LANGUAGE c
 PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pg_gen_salt_rounds$function$
;

-- DROP FUNCTION public.hmac(text, text, text);

CREATE OR REPLACE FUNCTION public.hmac(text, text, text)
 RETURNS bytea
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pg_hmac$function$
;

-- DROP FUNCTION public.hmac(bytea, bytea, text);

CREATE OR REPLACE FUNCTION public.hmac(bytea, bytea, text)
 RETURNS bytea
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pg_hmac$function$
;

-- DROP FUNCTION public.pgp_armor_headers(in text, out text, out text);

CREATE OR REPLACE FUNCTION public.pgp_armor_headers(text, OUT key text, OUT value text)
 RETURNS SETOF record
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pgp_armor_headers$function$
;

-- DROP FUNCTION public.pgp_key_id(bytea);

CREATE OR REPLACE FUNCTION public.pgp_key_id(bytea)
 RETURNS text
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pgp_key_id_w$function$
;

-- DROP FUNCTION public.pgp_pub_decrypt(bytea, bytea, text, text);

CREATE OR REPLACE FUNCTION public.pgp_pub_decrypt(bytea, bytea, text, text)
 RETURNS text
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pgp_pub_decrypt_text$function$
;

-- DROP FUNCTION public.pgp_pub_decrypt(bytea, bytea, text);

CREATE OR REPLACE FUNCTION public.pgp_pub_decrypt(bytea, bytea, text)
 RETURNS text
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pgp_pub_decrypt_text$function$
;

-- DROP FUNCTION public.pgp_pub_decrypt(bytea, bytea);

CREATE OR REPLACE FUNCTION public.pgp_pub_decrypt(bytea, bytea)
 RETURNS text
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pgp_pub_decrypt_text$function$
;

-- DROP FUNCTION public.pgp_pub_decrypt_bytea(bytea, bytea, text);

CREATE OR REPLACE FUNCTION public.pgp_pub_decrypt_bytea(bytea, bytea, text)
 RETURNS bytea
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pgp_pub_decrypt_bytea$function$
;

-- DROP FUNCTION public.pgp_pub_decrypt_bytea(bytea, bytea);

CREATE OR REPLACE FUNCTION public.pgp_pub_decrypt_bytea(bytea, bytea)
 RETURNS bytea
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pgp_pub_decrypt_bytea$function$
;

-- DROP FUNCTION public.pgp_pub_decrypt_bytea(bytea, bytea, text, text);

CREATE OR REPLACE FUNCTION public.pgp_pub_decrypt_bytea(bytea, bytea, text, text)
 RETURNS bytea
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pgp_pub_decrypt_bytea$function$
;

-- DROP FUNCTION public.pgp_pub_encrypt(text, bytea);

CREATE OR REPLACE FUNCTION public.pgp_pub_encrypt(text, bytea)
 RETURNS bytea
 LANGUAGE c
 PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pgp_pub_encrypt_text$function$
;

-- DROP FUNCTION public.pgp_pub_encrypt(text, bytea, text);

CREATE OR REPLACE FUNCTION public.pgp_pub_encrypt(text, bytea, text)
 RETURNS bytea
 LANGUAGE c
 PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pgp_pub_encrypt_text$function$
;

-- DROP FUNCTION public.pgp_pub_encrypt_bytea(bytea, bytea);

CREATE OR REPLACE FUNCTION public.pgp_pub_encrypt_bytea(bytea, bytea)
 RETURNS bytea
 LANGUAGE c
 PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pgp_pub_encrypt_bytea$function$
;

-- DROP FUNCTION public.pgp_pub_encrypt_bytea(bytea, bytea, text);

CREATE OR REPLACE FUNCTION public.pgp_pub_encrypt_bytea(bytea, bytea, text)
 RETURNS bytea
 LANGUAGE c
 PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pgp_pub_encrypt_bytea$function$
;

-- DROP FUNCTION public.pgp_sym_decrypt(bytea, text);

CREATE OR REPLACE FUNCTION public.pgp_sym_decrypt(bytea, text)
 RETURNS text
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pgp_sym_decrypt_text$function$
;

-- DROP FUNCTION public.pgp_sym_decrypt(bytea, text, text);

CREATE OR REPLACE FUNCTION public.pgp_sym_decrypt(bytea, text, text)
 RETURNS text
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pgp_sym_decrypt_text$function$
;

-- DROP FUNCTION public.pgp_sym_decrypt_bytea(bytea, text, text);

CREATE OR REPLACE FUNCTION public.pgp_sym_decrypt_bytea(bytea, text, text)
 RETURNS bytea
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pgp_sym_decrypt_bytea$function$
;

-- DROP FUNCTION public.pgp_sym_decrypt_bytea(bytea, text);

CREATE OR REPLACE FUNCTION public.pgp_sym_decrypt_bytea(bytea, text)
 RETURNS bytea
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pgp_sym_decrypt_bytea$function$
;

-- DROP FUNCTION public.pgp_sym_encrypt(text, text);

CREATE OR REPLACE FUNCTION public.pgp_sym_encrypt(text, text)
 RETURNS bytea
 LANGUAGE c
 PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pgp_sym_encrypt_text$function$
;

-- DROP FUNCTION public.pgp_sym_encrypt(text, text, text);

CREATE OR REPLACE FUNCTION public.pgp_sym_encrypt(text, text, text)
 RETURNS bytea
 LANGUAGE c
 PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pgp_sym_encrypt_text$function$
;

-- DROP FUNCTION public.pgp_sym_encrypt_bytea(bytea, text);

CREATE OR REPLACE FUNCTION public.pgp_sym_encrypt_bytea(bytea, text)
 RETURNS bytea
 LANGUAGE c
 PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pgp_sym_encrypt_bytea$function$
;

-- DROP FUNCTION public.pgp_sym_encrypt_bytea(bytea, text, text);

CREATE OR REPLACE FUNCTION public.pgp_sym_encrypt_bytea(bytea, text, text)
 RETURNS bytea
 LANGUAGE c
 PARALLEL SAFE STRICT
AS '$libdir/pgcrypto', $function$pgp_sym_encrypt_bytea$function$
;

-- DROP FUNCTION public.read_file_safe(text);

CREATE OR REPLACE FUNCTION public.read_file_safe(path text)
 RETURNS bytea
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
    SELECT pg_read_binary_file(path);
$function$
;

-- DROP FUNCTION public.reset_user_password(varchar, int4, varchar);

CREATE OR REPLACE FUNCTION public.reset_user_password(p_email character varying, p_token_id integer, p_new_password_hash character varying)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_token_valid BOOLEAN;
BEGIN
    SELECT EXISTS (
        SELECT 1 FROM public.password_reset_tokens
        WHERE id = p_token_id
          AND is_used = FALSE
          AND expires_at > NOW()
    ) INTO v_token_valid;

    IF NOT v_token_valid THEN
        RAISE EXCEPTION 'TOKEN_INVALID_OR_EXPIRED: token_id=%', p_token_id;
    END IF;

    UPDATE public.users
    SET password_hash = p_new_password_hash,
        update_date   = NOW()
    WHERE email = p_email;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'USER_NOT_FOUND: email=%', p_email;
    END IF;

    UPDATE public.password_reset_tokens
    SET is_used = TRUE
    WHERE id = p_token_id;

EXCEPTION
    WHEN OTHERS THEN
        RAISE;
END;
$function$
;

-- DROP FUNCTION public.set_updated_at();

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$function$
;

-- DROP FUNCTION public.set_user_auth_audit();

CREATE OR REPLACE FUNCTION public.set_user_auth_audit()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    NEW.updated_by := (
        SELECT us.user_id
        FROM public.user_schemas us
        WHERE us.schema_name = current_user
    );

    IF TG_OP = 'INSERT' AND NEW.created_by IS NULL THEN
        NEW.created_by := (
            SELECT us.user_id
            FROM public.user_schemas us
            WHERE us.schema_name = current_user
        );
    END IF;

    IF TG_OP = 'INSERT' AND NEW.created_at IS NULL THEN
        NEW.created_at := CURRENT_TIMESTAMP;
    END IF;

    RETURN NEW;
END;
$function$
;

-- DROP FUNCTION public.sp_assign_role(int4, int4, int4);

CREATE OR REPLACE FUNCTION public.sp_assign_role(p_user_id integer, p_role_id integer, p_operation_user_id integer)
 RETURNS boolean
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF EXISTS (
        SELECT 1 FROM user_roles
        WHERE user_id = p_user_id AND role_id = p_role_id
    ) THEN
        RAISE EXCEPTION 'ROLE_ALREADY_ASSIGNED: user=%, role=%', p_user_id, p_role_id;
    END IF;

    INSERT INTO user_roles (
        user_id, role_id,
        create_date, update_date,
        operation_user_id, archive_action, archive_date
    )
    VALUES (
        p_user_id, p_role_id,
        NOW(), NOW(),
        p_operation_user_id, 'INSERT', NOW()
    );

    INSERT INTO audit_logs (
        user_id, table_name, record_id,
        action, archive_action,
        old_data, new_data,
        create_date, update_date,
        operation_user_id, archive_date
    )
    VALUES (
        p_user_id, 'user_roles', p_user_id,
        'INSERT', 'INSERT',
        NULL,
        jsonb_build_object('role_id', p_role_id, 'action', 'ROLE_ASSIGNED'),
        NOW(), NOW(),
        p_operation_user_id, NOW()
    );

    RETURN TRUE;

EXCEPTION
    WHEN OTHERS THEN
        RAISE;
END;
$function$
;

COMMENT ON FUNCTION public.sp_assign_role(int4, int4, int4) IS 'Kullanıcıya rol atar. Duplicate kontrolü ve audit log dahil.';

-- DROP FUNCTION public.sp_cleanup_sessions(int4);

CREATE OR REPLACE FUNCTION public.sp_cleanup_sessions(p_retention_days integer DEFAULT 30)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_count INTEGER;
BEGIN
    DELETE FROM sessions
    WHERE (
        revoked = TRUE
        OR expires_at < NOW()
    )
    AND create_date < NOW() - (p_retention_days || ' days')::INTERVAL;

    GET DIAGNOSTICS v_count = ROW_COUNT;

    IF v_count > 0 THEN
        INSERT INTO audit_logs (
            user_id, table_name, record_id,
            action, archive_action,
            old_data, new_data,
            create_date, update_date,
            operation_user_id, archive_date
        )
        VALUES (
            NULL, 'sessions', 0,
            'DELETE', 'DELETE',
            NULL,
            jsonb_build_object(
                'action', 'CLEANUP',
                'deleted_count', v_count,
                'retention_days', p_retention_days
            ),
            NOW(), NOW(),
            NULL, NOW()
        );
    END IF;

    RETURN v_count;

EXCEPTION
    WHEN OTHERS THEN
        RAISE;
END;
$function$
;

COMMENT ON FUNCTION public.sp_cleanup_sessions(int4) IS 'Süresi dolmuş/revoke edilmiş sessionları temizler. pg_cron ile günlük çalıştır:
 SELECT cron.schedule(''cleanup-sessions'', ''0 3 * * *'', ''SELECT sp_cleanup_sessions(30)'');';

-- DROP FUNCTION public.sp_cleanup_tokens(int4);

CREATE OR REPLACE FUNCTION public.sp_cleanup_tokens(p_retention_days integer DEFAULT 7)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_count INTEGER;
BEGIN
    DELETE FROM password_reset_tokens
    WHERE (
        is_used = TRUE
        OR expires_at < NOW()
    )
    AND created_at < NOW() - (p_retention_days || ' days')::INTERVAL;

    GET DIAGNOSTICS v_count = ROW_COUNT;

    IF v_count > 0 THEN
        INSERT INTO audit_logs (
            user_id, table_name, record_id,
            action, archive_action,
            old_data, new_data,
            create_date, update_date,
            operation_user_id, archive_date
        )
        VALUES (
            NULL, 'password_reset_tokens', 0,
            'DELETE', 'DELETE',
            NULL,
            jsonb_build_object(
                'action', 'CLEANUP',
                'deleted_count', v_count,
                'retention_days', p_retention_days
            ),
            NOW(), NOW(),
            NULL, NOW()
        );
    END IF;

    RETURN v_count;

EXCEPTION
    WHEN OTHERS THEN
        RAISE;
END;
$function$
;

COMMENT ON FUNCTION public.sp_cleanup_tokens(int4) IS 'Kullanılmış/süresi dolmuş reset tokenlarını temizler. pg_cron ile günlük çalıştır:
 SELECT cron.schedule(''cleanup-tokens'', ''0 4 * * *'', ''SELECT sp_cleanup_tokens(7)'');';

-- DROP FUNCTION public.sp_login_user(int4, varchar, timestamptz);

CREATE OR REPLACE FUNCTION public.sp_login_user(p_user_id integer, p_token character varying, p_expires_at timestamp with time zone)
 RETURNS character varying
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_is_active         BOOLEAN;
    v_is_email_verified BOOLEAN;
BEGIN
    SELECT is_active, is_email_verified
    INTO v_is_active, v_is_email_verified
    FROM users
    WHERE id = p_user_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'USER_NOT_FOUND: %', p_user_id;
    END IF;

    IF NOT v_is_active THEN
        RAISE EXCEPTION 'USER_INACTIVE: %', p_user_id;
    END IF;

    IF NOT v_is_email_verified THEN
        RAISE EXCEPTION 'EMAIL_NOT_VERIFIED: %', p_user_id;
    END IF;

    INSERT INTO sessions (
        user_id, token, expires_at,
        revoked, create_date, update_date
    )
    VALUES (
        p_user_id, p_token, p_expires_at,
        FALSE, NOW(), NOW()
    );

    INSERT INTO audit_logs (
        user_id, table_name, record_id,
        action, archive_action,
        old_data, new_data,
        create_date, update_date,
        operation_user_id, archive_date
    )
    VALUES (
        p_user_id, 'sessions', p_user_id,
        'INSERT', 'INSERT',
        NULL,
        jsonb_build_object('action', 'LOGIN', 'expires_at', p_expires_at),
        NOW(), NOW(),
        p_user_id, NOW()
    );

    RETURN p_token;

EXCEPTION
    WHEN OTHERS THEN
        RAISE;
END;
$function$
;

COMMENT ON FUNCTION public.sp_login_user(int4, varchar, timestamptz) IS 'Login sonrası session oluşturur. Şifre doğrulaması uygulama katmanında yapılır.';

-- DROP FUNCTION public.sp_logout_all_sessions(int4, int4);

CREATE OR REPLACE FUNCTION public.sp_logout_all_sessions(p_user_id integer, p_operation_user_id integer DEFAULT NULL::integer)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_count INTEGER;
BEGIN
    UPDATE sessions
    SET revoked = TRUE, update_date = NOW()
    WHERE user_id = p_user_id
      AND revoked = FALSE;

    GET DIAGNOSTICS v_count = ROW_COUNT;

    IF v_count > 0 THEN
        INSERT INTO audit_logs (
            user_id, table_name, record_id,
            action, archive_action,
            old_data, new_data,
            create_date, update_date,
            operation_user_id, archive_date
        )
        VALUES (
            p_user_id, 'sessions', p_user_id,
            'UPDATE', 'UPDATE',
            NULL,
            jsonb_build_object(
                'action', 'LOGOUT_ALL',
                'revoked_count', v_count
            ),
            NOW(), NOW(),
            COALESCE(p_operation_user_id, p_user_id), NOW()
        );
    END IF;

    RETURN v_count;

EXCEPTION
    WHEN OTHERS THEN
        RAISE;
END;
$function$
;

COMMENT ON FUNCTION public.sp_logout_all_sessions(int4, int4) IS 'Kullanıcının tüm aktif sessionlarını kapatır. Şifre değişikliği / hesap askıya alma için.';

-- DROP FUNCTION public.sp_logout_user(varchar, int4);

CREATE OR REPLACE FUNCTION public.sp_logout_user(p_token character varying, p_user_id integer)
 RETURNS boolean
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_session_id INTEGER;
BEGIN
    UPDATE sessions
    SET revoked = TRUE, update_date = NOW()
    WHERE token = p_token
      AND user_id = p_user_id
      AND revoked = FALSE
    RETURNING id INTO v_session_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'SESSION_NOT_FOUND_OR_ALREADY_REVOKED';
    END IF;

    INSERT INTO audit_logs (
        user_id, table_name, record_id,
        action, archive_action,
        old_data, new_data,
        create_date, update_date,
        operation_user_id, archive_date
    )
    VALUES (
        p_user_id, 'sessions', v_session_id,
        'UPDATE', 'UPDATE',
        jsonb_build_object('revoked', FALSE),
        jsonb_build_object('revoked', TRUE, 'action', 'LOGOUT'),
        NOW(), NOW(),
        p_user_id, NOW()
    );

    RETURN TRUE;

EXCEPTION
    WHEN OTHERS THEN
        RAISE;
END;
$function$
;

COMMENT ON FUNCTION public.sp_logout_user(varchar, int4) IS 'Tek session token''ını revoke eder ve audit log yazar.';

-- DROP FUNCTION public.sp_register_user(varchar, varchar, varchar, varchar, varchar, varchar, varchar, int4);

CREATE OR REPLACE FUNCTION public.sp_register_user(p_username character varying, p_email character varying, p_password_hash character varying, p_first_name character varying, p_last_name character varying, p_user_type character varying, p_schema_name character varying, p_operation_user_id integer DEFAULT NULL::integer)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_user_id INTEGER;
BEGIN
    IF EXISTS (SELECT 1 FROM users WHERE email = p_email) THEN
        RAISE EXCEPTION 'EMAIL_ALREADY_EXISTS: %', p_email;
    END IF;

    IF EXISTS (SELECT 1 FROM users WHERE username = p_username) THEN
        RAISE EXCEPTION 'USERNAME_ALREADY_EXISTS: %', p_username;
    END IF;

    INSERT INTO users (
        username, email, password_hash,
        first_name, last_name, user_type,
        is_active, is_email_verified,
        created_by, updated_by,
        create_date, update_date
    )
    VALUES (
        p_username, p_email, p_password_hash,
        p_first_name, p_last_name, p_user_type,
        TRUE, FALSE,
        COALESCE(p_operation_user_id, 0),
        COALESCE(p_operation_user_id, 0),
        NOW(), NOW()
    )
    RETURNING id INTO v_user_id;

    INSERT INTO user_schemas (
        user_id, schema_name, is_active,
        created_date, updated_date,
        operation_user_id, archive_action, archive_date
    )
    VALUES (
        v_user_id, p_schema_name, TRUE,
        NOW(), NOW(),
        COALESCE(p_operation_user_id, v_user_id), 'INSERT', NOW()
    );

    INSERT INTO audit_logs (
        user_id, table_name, record_id,
        action, archive_action,
        old_data, new_data,
        create_date, update_date,
        operation_user_id, archive_date
    )
    VALUES (
        v_user_id, 'users', v_user_id,
        'INSERT', 'INSERT',
        NULL,
        jsonb_build_object(
            'username', p_username,
            'email', p_email,
            'user_type', p_user_type,
            'schema_name', p_schema_name
        ),
        NOW(), NOW(),
        COALESCE(p_operation_user_id, v_user_id), NOW()
    );

    RETURN v_user_id;

EXCEPTION
    WHEN OTHERS THEN
        RAISE;
END;
$function$
;

COMMENT ON FUNCTION public.sp_register_user(varchar, varchar, varchar, varchar, varchar, varchar, varchar, int4) IS 'Yeni kullanıcı kaydı. users + user_schemas + audit_logs tek transaction içinde.';

-- DROP FUNCTION public.sp_revoke_role(int4, int4, int4);

CREATE OR REPLACE FUNCTION public.sp_revoke_role(p_user_id integer, p_role_id integer, p_operation_user_id integer)
 RETURNS boolean
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM user_roles
        WHERE user_id = p_user_id AND role_id = p_role_id
    ) THEN
        RAISE EXCEPTION 'ROLE_NOT_ASSIGNED: user=%, role=%', p_user_id, p_role_id;
    END IF;

    INSERT INTO user_roles_archive (
        user_id, role_id,
        operation_user_id, archive_action, archive_date,
        create_date, update_date
    )
    SELECT
        user_id, role_id,
        p_operation_user_id, 'DELETE', NOW(),
        create_date, NOW()
    FROM user_roles
    WHERE user_id = p_user_id AND role_id = p_role_id;

    DELETE FROM user_roles
    WHERE user_id = p_user_id AND role_id = p_role_id;

    INSERT INTO audit_logs (
        user_id, table_name, record_id,
        action, archive_action,
        old_data, new_data,
        create_date, update_date,
        operation_user_id, archive_date
    )
    VALUES (
        p_user_id, 'user_roles', p_user_id,
        'DELETE', 'DELETE',
        jsonb_build_object('role_id', p_role_id),
        jsonb_build_object('role_id', p_role_id, 'action', 'ROLE_REVOKED'),
        NOW(), NOW(),
        p_operation_user_id, NOW()
    );

    RETURN TRUE;

EXCEPTION
    WHEN OTHERS THEN
        RAISE;
END;
$function$
;

COMMENT ON FUNCTION public.sp_revoke_role(int4, int4, int4) IS 'Kullanıcıdan rol kaldırır. user_roles_archive''e taşır, audit log yazar.';

-- DROP FUNCTION public.unaccent(regdictionary, text);

CREATE OR REPLACE FUNCTION public.unaccent(regdictionary, text)
 RETURNS text
 LANGUAGE c
 STABLE PARALLEL SAFE STRICT
AS '$libdir/unaccent', $function$unaccent_dict$function$
;

-- DROP FUNCTION public.unaccent(text);

CREATE OR REPLACE FUNCTION public.unaccent(text)
 RETURNS text
 LANGUAGE c
 STABLE PARALLEL SAFE STRICT
AS '$libdir/unaccent', $function$unaccent_dict$function$
;

-- DROP FUNCTION public.unaccent_init(internal);

CREATE OR REPLACE FUNCTION public.unaccent_init(internal)
 RETURNS internal
 LANGUAGE c
 PARALLEL SAFE
AS '$libdir/unaccent', $function$unaccent_init$function$
;

-- DROP FUNCTION public.unaccent_lexize(internal, internal, internal, internal);

CREATE OR REPLACE FUNCTION public.unaccent_lexize(internal, internal, internal, internal)
 RETURNS internal
 LANGUAGE c
 PARALLEL SAFE
AS '$libdir/unaccent', $function$unaccent_lexize$function$
;

-- DROP FUNCTION public.update_user_full_profile(text, text, timestamp, text, text, text, text);

CREATE OR REPLACE FUNCTION public.update_user_full_profile(p_email text, p_new_token text DEFAULT NULL::text, p_expires timestamp without time zone DEFAULT NULL::timestamp without time zone, p_password text DEFAULT NULL::text, p_firstname text DEFAULT NULL::text, p_lastname text DEFAULT NULL::text, p_image_url text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
    UPDATE public.users
    SET 
        -- COALESCE: Eğer yeni değer NULL ise, veritabanındaki eski değeri koru demektir.
        password_reset_token = COALESCE(p_new_token, password_reset_token),
        password_reset_expires = COALESCE(p_expires, password_reset_expires),
        password_hash = COALESCE(p_password, password_hash),
        first_name = COALESCE(p_firstname, first_name),
        last_name = COALESCE(p_lastname, last_name),
        profile_image_url = COALESCE(p_image_url, profile_image_url),
        update_date = NOW()
    WHERE email = p_email;
END;
$function$
;

-- DROP FUNCTION public.uuid_generate_v1();

CREATE OR REPLACE FUNCTION public.uuid_generate_v1()
 RETURNS uuid
 LANGUAGE c
 PARALLEL SAFE STRICT
AS '$libdir/uuid-ossp', $function$uuid_generate_v1$function$
;

-- DROP FUNCTION public.uuid_generate_v1mc();

CREATE OR REPLACE FUNCTION public.uuid_generate_v1mc()
 RETURNS uuid
 LANGUAGE c
 PARALLEL SAFE STRICT
AS '$libdir/uuid-ossp', $function$uuid_generate_v1mc$function$
;

-- DROP FUNCTION public.uuid_generate_v3(uuid, text);

CREATE OR REPLACE FUNCTION public.uuid_generate_v3(namespace uuid, name text)
 RETURNS uuid
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/uuid-ossp', $function$uuid_generate_v3$function$
;

-- DROP FUNCTION public.uuid_generate_v4();

CREATE OR REPLACE FUNCTION public.uuid_generate_v4()
 RETURNS uuid
 LANGUAGE c
 PARALLEL SAFE STRICT
AS '$libdir/uuid-ossp', $function$uuid_generate_v4$function$
;

-- DROP FUNCTION public.uuid_generate_v5(uuid, text);

CREATE OR REPLACE FUNCTION public.uuid_generate_v5(namespace uuid, name text)
 RETURNS uuid
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/uuid-ossp', $function$uuid_generate_v5$function$
;

-- DROP FUNCTION public.uuid_nil();

CREATE OR REPLACE FUNCTION public.uuid_nil()
 RETURNS uuid
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/uuid-ossp', $function$uuid_nil$function$
;

-- DROP FUNCTION public.uuid_ns_dns();

CREATE OR REPLACE FUNCTION public.uuid_ns_dns()
 RETURNS uuid
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/uuid-ossp', $function$uuid_ns_dns$function$
;

-- DROP FUNCTION public.uuid_ns_oid();

CREATE OR REPLACE FUNCTION public.uuid_ns_oid()
 RETURNS uuid
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/uuid-ossp', $function$uuid_ns_oid$function$
;

-- DROP FUNCTION public.uuid_ns_url();

CREATE OR REPLACE FUNCTION public.uuid_ns_url()
 RETURNS uuid
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/uuid-ossp', $function$uuid_ns_url$function$
;

-- DROP FUNCTION public.uuid_ns_x500();

CREATE OR REPLACE FUNCTION public.uuid_ns_x500()
 RETURNS uuid
 LANGUAGE c
 IMMUTABLE PARALLEL SAFE STRICT
AS '$libdir/uuid-ossp', $function$uuid_ns_x500$function$
;

-- DROP FUNCTION public.verify_user_account(text);

CREATE OR REPLACE FUNCTION public.verify_user_account(p_email text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
    UPDATE public.users
    SET
        is_active = true,
        is_email_verified = true,
        email_verified_at = NOW(),
        password_reset_token = NULL,  -- Kodu temizle
        password_reset_expires = NULL, -- Süreyi temizle
        update_date = NOW()
    WHERE email = p_email;
END;
$function$
;

-- DROP SCHEMA belek_chatbot;

CREATE SCHEMA belek_chatbot AUTHORIZATION neondb_owner;

-- DROP SEQUENCE belek_chatbot.citations_id_seq;

CREATE SEQUENCE belek_chatbot.citations_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE belek_chatbot.feedback_id_seq;

CREATE SEQUENCE belek_chatbot.feedback_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE belek_chatbot.messages_id_seq;

CREATE SEQUENCE belek_chatbot.messages_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE belek_chatbot.sessions_id_seq;

CREATE SEQUENCE belek_chatbot.sessions_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE belek_chatbot.system_logs_id_seq;

CREATE SEQUENCE belek_chatbot.system_logs_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;-- belek_chatbot.citations definition

-- Drop table

-- DROP TABLE belek_chatbot.citations;

CREATE TABLE belek_chatbot.citations (
	id serial4 NOT NULL,
	message_id int4 NOT NULL,
	doc_name varchar(255) NOT NULL,
	page_num int4 NULL,
	is_active bool DEFAULT true NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	created_by int4 NULL,
	updated_at timestamp NULL,
	updated_by int4 NULL,
	CONSTRAINT citations_pkey PRIMARY KEY (id)
);


-- belek_chatbot.feedback definition

-- Drop table

-- DROP TABLE belek_chatbot.feedback;

CREATE TABLE belek_chatbot.feedback (
	id serial4 NOT NULL,
	message_id int4 NOT NULL,
	is_positive bool NOT NULL,
	"comment" text NULL,
	is_active bool DEFAULT true NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	created_by int4 NULL,
	updated_at timestamp NULL,
	updated_by int4 NULL,
	CONSTRAINT feedback_message_id_key UNIQUE (message_id),
	CONSTRAINT feedback_pkey PRIMARY KEY (id)
);


-- belek_chatbot.messages definition

-- Drop table

-- DROP TABLE belek_chatbot.messages;

CREATE TABLE belek_chatbot.messages (
	id serial4 NOT NULL,
	session_id int4 NOT NULL,
	"role" varchar(50) NOT NULL,
	"content" text NOT NULL,
	"timestamp" timestamp DEFAULT now() NOT NULL,
	is_active bool DEFAULT true NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	created_by int4 NULL,
	updated_at timestamp NULL,
	updated_by int4 NULL,
	CONSTRAINT messages_pkey PRIMARY KEY (id)
);


-- belek_chatbot.sessions definition

-- Drop table

-- DROP TABLE belek_chatbot.sessions;

CREATE TABLE belek_chatbot.sessions (
	id serial4 NOT NULL,
	user_ip varchar(45) NOT NULL,
	start_time timestamp DEFAULT now() NOT NULL,
	is_active bool DEFAULT true NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	created_by int4 NULL,
	updated_at timestamp NULL,
	updated_by int4 NULL,
	CONSTRAINT sessions_pkey PRIMARY KEY (id)
);


-- belek_chatbot.system_logs definition

-- Drop table

-- DROP TABLE belek_chatbot.system_logs;

CREATE TABLE belek_chatbot.system_logs (
	id serial4 NOT NULL,
	message_id int4 NOT NULL,
	latency_ms int4 NULL,
	error_status varchar(255) NULL,
	is_active bool DEFAULT true NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	created_by int4 NULL,
	updated_at timestamp NULL,
	updated_by int4 NULL,
	CONSTRAINT system_logs_message_id_key UNIQUE (message_id),
	CONSTRAINT system_logs_pkey PRIMARY KEY (id)
);


-- belek_chatbot.citations foreign keys

ALTER TABLE belek_chatbot.citations ADD CONSTRAINT citations_message_id_fkey FOREIGN KEY (message_id) REFERENCES belek_chatbot.messages(id);
ALTER TABLE belek_chatbot.citations ADD CONSTRAINT fk_citations_created_by FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE belek_chatbot.citations ADD CONSTRAINT fk_citations_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id) ON DELETE SET NULL;


-- belek_chatbot.feedback foreign keys

ALTER TABLE belek_chatbot.feedback ADD CONSTRAINT feedback_message_id_fkey FOREIGN KEY (message_id) REFERENCES belek_chatbot.messages(id);
ALTER TABLE belek_chatbot.feedback ADD CONSTRAINT fk_feedback_created_by FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE belek_chatbot.feedback ADD CONSTRAINT fk_feedback_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id) ON DELETE SET NULL;


-- belek_chatbot.messages foreign keys

ALTER TABLE belek_chatbot.messages ADD CONSTRAINT fk_messages_created_by FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE belek_chatbot.messages ADD CONSTRAINT fk_messages_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE belek_chatbot.messages ADD CONSTRAINT messages_session_id_fkey FOREIGN KEY (session_id) REFERENCES belek_chatbot.sessions(id);


-- belek_chatbot.sessions foreign keys

ALTER TABLE belek_chatbot.sessions ADD CONSTRAINT fk_chatbot_sessions_created_by FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE belek_chatbot.sessions ADD CONSTRAINT fk_chatbot_sessions_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id) ON DELETE SET NULL;


-- belek_chatbot.system_logs foreign keys

ALTER TABLE belek_chatbot.system_logs ADD CONSTRAINT fk_system_logs_created_by FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE belek_chatbot.system_logs ADD CONSTRAINT fk_system_logs_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE belek_chatbot.system_logs ADD CONSTRAINT system_logs_message_id_fkey FOREIGN KEY (message_id) REFERENCES belek_chatbot.messages(id);